#!/usr/bin/env bash
# Daily slot-persistence failure observation (LP-0MSI1RWLM007N367 F4).
#
# Reuses scripts/slot-persistence-correlate.py to compute the daily
# slot_save/slot_restore failure rate + load context from the live proxy
# logs, and appends a compact line to the observation log. Run once per day
# during the 7-day post-fix window (survives the day 3-slot -> night 8-slot
# config cycle because it reads the full day's logs).
#
# Usage:
#   ./scripts/slot-persistence-failures.sh                        # today (00:00 -> now)
#   ./scripts/slot-persistence-failures.sh --date 2026-08-08       # a specific day
#   ./scripts/slot-persistence-failures.sh --log-dir /var/log/llama-proxy
#   ./scripts/slot-persistence-failures.sh --dry-run              # print line only
#
# Output: appends to docs/dev/slot-thrashing-investigation/observation-log.md
# (or the path given by --log-file). The line format:
#   | YYYY-MM-DD | save X/Y (Z%) | restore A/B (C%) | max concurrent streams | fallbacks |
#
# Exit codes:
#   0 - success (even when the line is a zero-failure baseline)
#   1 - correlation script failed or log dir missing

set -eo pipefail

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
CORRELATE="$SCRIPT_DIR/slot-persistence-correlate.py"
REPO_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"
DEFAULT_LOG_FILE="$REPO_ROOT/docs/dev/slot-thrashing-investigation/observation-log.md"
LOG_DIR="/var/log/llama-proxy"
DATE="$(date +%F)"
DRY_RUN=0
LOG_FILE="$DEFAULT_LOG_FILE"

usage() {
    sed -n '2,20p' "$0" | sed 's/^# \{0,1\}//'
    exit 0
}

while [ $# -gt 0 ]; do
    case "$1" in
        --date) DATE="$2"; shift 2 ;;
        --log-dir) LOG_DIR="$2"; shift 2 ;;
        --log-file) LOG_FILE="$2"; shift 2 ;;
        --dry-run) DRY_RUN=1; shift ;;
        -h|--help) usage ;;
        *) echo "error: unknown option: $1" >&2; exit 1 ;;
    esac
done

if [ ! -d "$LOG_DIR" ]; then
    echo "error: log directory not found: $LOG_DIR" >&2
    exit 1
fi

START="${DATE} 00:00:00"
END="${DATE} 23:59:59"

# --json output of the correlation script for the full day.
JSON="$(python3 "$CORRELATE" --log-dir "$LOG_DIR" \
    --start "$START" --end "$END" --json 2>/dev/null || true)"

if [ -z "$JSON" ]; then
    echo "error: correlation script produced no output for $DATE" >&2
    exit 1
fi

SAVE_FAIL="$(echo "$JSON" | python3 -c "import json,sys; d=json.load(sys.stdin); print(d['totals']['slot_save_failed'])")"
SAVE_OK="$(echo "$JSON" | python3 -c "import json,sys; d=json.load(sys.stdin); print(d['totals']['slot_save_success'])")"
RESTORE_FAIL="$(echo "$JSON" | python3 -c "import json,sys; d=json.load(sys.stdin); print(d['totals']['slot_restore_failed'])")"
RESTORE_OK="$(echo "$JSON" | python3 -c "import json,sys; d=json.load(sys.stdin); print(d['totals']['slot_restore_success'])")"
SAVE_RATE="$(echo "$JSON" | python3 -c "import json,sys; d=json.load(sys.stdin); print(d['failure_rate_pct']['save'])")"
RESTORE_RATE="$(echo "$JSON" | python3 -c "import json,sys; d=json.load(sys.stdin); print(d['failure_rate_pct']['restore'])")"
MAX_STREAMS="$(echo "$JSON" | python3 -c "import json,sys; d=json.load(sys.stdin); print(d['load_context']['max_active_local_streams_at_failure'])")"
FALLBACKS="$(echo "$JSON" | python3 -c "
import json,sys
d=json.load(sys.stdin)
n=sum(f.get('concurrency_fallbacks_in_window',0) for f in d['failures'])
print(n)
")"

LINE="| $DATE | save $SAVE_FAIL/$((SAVE_FAIL + SAVE_OK)) (${SAVE_RATE}%) | restore $RESTORE_FAIL/$((RESTORE_FAIL + RESTORE_OK)) (${RESTORE_RATE}%) | $MAX_STREAMS | $FALLBACKS |"

if [ "$DRY_RUN" = "1" ]; then
    echo "$LINE"
    exit 0
fi

# Append to the observation log (creating header on first run).
if [ ! -f "$LOG_FILE" ]; then
    mkdir -p "$(dirname "$LOG_FILE")"
    cat > "$LOG_FILE" << 'HEADER'
# Slot-persistence failure observation log (LP-0MSI1RWLM007N367 F4)

7-day post-fix observation window for the load-aware save gate + timeout
rebalance (commit 9acfebc). Generated by `scripts/slot-persistence-failures.sh`.

| Date | slot_save failed/total (%) | slot_restore failed/total (%) | max concurrent streams at failure | concurrency fallbacks near failures |
|------|----------------------------|-------------------------------|-----------------------------------|-------------------------------------|
HEADER
fi

echo "$LINE" >> "$LOG_FILE"
echo "appended: $LINE"
echo "log: $LOG_FILE"
exit 0
